blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/GreenMeteor/discussions
    about: Please ask and answer questions here.
  - name: HumHub Questions
    url: https://community.humhub.com
    about: Please use the HumHub community site for general HumHub questions.
